server {
  listen 80;

  location / {                          # Angular 路由 fallback
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }

  location /api/ {                      # 轉發給後端容器
    proxy_pass http://survey-api:8080/api/;
    proxy_set_header Host $http_host;   # 帶 port 的 Host，Spring 才知道這是「同源」請求
    proxy_set_header X-Real-IP $remote_addr;
  }
}
